#!/bin/bash

# Extract and format the data using jq, awk, and sed
jq -r '[.name, .height, .weight, (.types[]?.type.name // empty)] | @tsv' pokemon_data.json | \
awk -F'\t' '{
    # Convert height and weight from decimetres/decigrams to metres/kg
    height_m = $2/10
    weight_kg = $3/10
    
    # Build type string - handle multiple types
    type_str = ""
    for (i=4; i<=NF; i++) {
        if (type_str == "") {
            type_str = $i
        } else {
            type_str = type_str " and " $i
        }
    }
    
    # Capitalize first letter of name
    name = toupper(substr($1,1,1)) substr($1,2)
    
    # Capitalize first letter of each type
    gsub(/\band\b/, "and", type_str)
    split(type_str, types_arr, " and ")
    type_str = ""
    for (j in types_arr) {
        if (type_str != "") type_str = type_str " and "
        type_str = type_str toupper(substr(types_arr[j],1,1)) substr(types_arr[j],2)
    }
    
    # Remove trailing .0 from whole numbers to match sample format
    formatted_weight = weight_kg
    formatted_height = height_m
    if (weight_kg == int(weight_kg)) formatted_weight = int(weight_kg)
    if (height_m == int(height_m)) formatted_height = int(height_m)
    
    printf "%s is of type %s, weighs %skg, and is %sm tall.\n", name, type_str, formatted_weight, formatted_height
}