#!/bin/bash

jq -r '[.name, .height, .weight, (.types[]?.type.name // empty)] | @tsv' pokemon_data.json | \
awk -F'\t' '{
    # Convert height and weight
    height_m = $2/10
    weight_kg = $3/10
    
    # Build type string
    type_str = ""
    for (i=4; i<=NF; i++) {
        if (type_str == "") {
            type_str = $i
        } else {
            type_str = type_str " and " $i
        }
    }
    
    # Capitalize name and types
    name = toupper(substr($1,1,1)) substr($1,2)
    
    # Capitalize types properly
    split(type_str, types_arr, " and ")
    type_str = ""
    for (j in types_arr) {
        if (type_str != "") type_str = type_str " and "
        type_str = type_str toupper(substr(types_arr[j],1,1)) substr(types_arr[j],2)
    }
    
    # Format without trailing zeros
    height_formatted = height_m
    weight_formatted = weight_kg
    gsub(/\.0+$/, "", height_formatted)
    gsub(/\.0+$/, "", weight_formatted)
    
    print name " is of type " type_str ", weighs " weight_formatted "kg, and is " height_formatted "m tall."
}'